apiVersion: v1
kind: Service
metadata:
  name: heart-disease
spec:
  type: LoadBalancer
  selector:
    app: heart-disease
  ports:
    - name: api
      port: 8000
      targetPort: 8000
    - name: mlflow
      port: 5000
      targetPort: 5000
